### ISSUE TITLE
Wrong type of fuels. (Colombia)

### ISSUE THREAD

**Issue by ordonezgs** [TheCre8r/WME-BackEnd-Data#6] opened 2018-12-31 15:23 UTC
The Script isn't working at all, it shows only in this case the Diesel but in the reality it appears another prices too.
<img width="1280" alt="captura de pantalla 2018-12-31 a la s 10 18 22 a m" src="https://user-images.githubusercontent.com/17103864/50562868-f345e900-0ce5-11e9-88f8-842efdaa0874.png">
![img_3542](https://user-images.githubusercontent.com/17103864/50562871-f8a33380-0ce5-11e9-8cbc-84fd147412c3.jpg)

[Do not read or disclose image meta data.]

**Comment by santy2001** [comment] 2019-01-05 21:18
PL Requested of the place mentioned.

https://www.waze.com/es-419/editor?env=row&lon=-73.11473&lat=7.10760&zoom=6&venues=188022855.1880163015.15306966

**Comment by TheCre8r** [comment] 2020-11-30 19:48
Can you please verify this has been resolved in the latest version?

**Comment by ordonezgs** [comment] 2020-12-16 22:52
It seems to; I haven’t checked for natural gas station prices yet. There is some kind of typo in some of the gas prices due to JS string thing “ ‘ ” in gas prices different from regular.

**Comment by jm6087** [comment] 2020-12-17 03:00
ordonezgs,
Can you provide a PL of an example? 

Thanks

**Comment by TheCre8r** [comment] 2023-04-18 12:31
Can you confirm if the issue is still present?

**Comment by TheCre8r** [comment] 2024-07-08 01:20
As this has been inactive for over 1 year. I am closing this issue.

**Closed by TheCre8r** 2024-07-08 01:20 UTC
Labels: Gas Stations, Planned
